
CREATE TABLE campaign_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  icon TEXT NOT NULL,
  thumbnail_url TEXT,
  is_active BOOLEAN DEFAULT 1,
  wheel_segments TEXT NOT NULL,
  wheel_colors TEXT NOT NULL,
  pointer_color TEXT DEFAULT '#ef4444',
  background_color TEXT DEFAULT '#ffffff',
  background_gradient_enabled BOOLEAN DEFAULT 0,
  background_gradient_start TEXT,
  background_gradient_end TEXT,
  background_gradient_direction TEXT DEFAULT 'to-bottom',
  background_image_url TEXT,
  logo_position TEXT DEFAULT 'center',
  confetti_enabled BOOLEAN DEFAULT 1,
  sound_enabled BOOLEAN DEFAULT 1,
  sound_settings TEXT DEFAULT '{"spin":true,"win":true,"noWin":true}',
  font_family TEXT DEFAULT 'Inter',
  font_size INTEGER DEFAULT 16,
  wheel_border_thickness INTEGER DEFAULT 3,
  wheel_border_color TEXT DEFAULT '#ffffff',
  pointer_style TEXT DEFAULT 'arrow',
  spin_button_text TEXT DEFAULT 'SPIN',
  spin_button_color TEXT DEFAULT '#6366f1',
  spin_button_border_radius INTEGER DEFAULT 40,
  spin_button_pulse_enabled BOOLEAN DEFAULT 1,
  spin_duration_seconds INTEGER DEFAULT 5,
  border_enabled BOOLEAN DEFAULT 0,
  border_theme TEXT,
  border_default_enabled BOOLEAN DEFAULT 1,
  border_default_color TEXT DEFAULT '#FFFFFF',
  border_default_thickness INTEGER DEFAULT 10,
  border_custom_colors TEXT,
  border_bulb_shape TEXT DEFAULT 'circle',
  border_bulb_count INTEGER DEFAULT 24,
  border_bulb_size INTEGER DEFAULT 10,
  border_blink_speed TEXT DEFAULT 'medium',
  border_connector_ring_enabled BOOLEAN DEFAULT 0,
  border_connector_ring_color TEXT DEFAULT '#FFFFFF',
  border_connector_ring_thickness INTEGER DEFAULT 6,
  lead_form_fields TEXT NOT NULL,
  redemption_instructions TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
